//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class TreeView {
	
	protected System.Web.UI.WebControls.Content Content1;
	
	protected System.Web.UI.WebControls.SiteMapDataSource MainSMDS;
	
	protected System.Web.UI.WebControls.TreeView TreeView1;
	
	protected System.Web.UI.WebControls.Menu Menu1;
}
